steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v2
  with:
    token: 74ede08f-1d0d-4610-8edd-f76c55f507a6 # not required for public repos
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
